name: Zip Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set Up PHP with WP-CLI
        uses: shivammathur/setup-php@2.22.0
        with:
          tools: wp
          php-version: 8.0

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Configure WP-CLI dist-archive-command
        run: |
          wp package install wp-cli/dist-archive-command

      - name: Build Plugin Zip
        run: |
          wp dist-archive ${{ env.BUILD_FOLDER }}

      - name: Save to Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.zip"
          tags: true
